<?php

namespace App\Tests\Func;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;


class UserConstraintTest extends AbstractEndPoint
{
    private string $tooShortUsernameUserPayload = '{"username": "shor", "email": "hard@gmail.com", "password": "password"}';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }

    public function testUsernameConstraint() : void
    {
        $response = $this->getResponseFromRequest(
            Request::METHOD_POST,
            "/users",
            $this->tooShortUsernameUserPayload,
        );

        // Username length constraint should be triggered and generate a 422 http error
        self::assertEquals(Response::HTTP_UNPROCESSABLE_ENTITY, $response->getStatusCode());
    }
}